# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions) (experimental)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not) (experimental)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: brave.exe
  1: 
    - discord.exe
    - teams.exe
    - zoom.exe
    - g2m*.exe
    - gamebar.exe
    - VoiceAttack.exe
    - EDDI.exe
    - atmgr.exe
    - g2mui.exe
  2: 
    - gw.exe
    - Gw2-64.exe
    - Blish HUD.exe
    - DarkSoulsRemastered.exe
    - FactoryGame.exe
    - 7DaysToDie.exe
    - ConanSandbox.exe
    - FSD.exe
    - FSD-Win64-Shipping.exe
    - destiny2.exe
    - EDF5.exe
    - EDLaunch.exe
    - factorio.exe
    - valheim.exe
    - vermintide2.exe
    - vermintide2_dx12.exe
    - Astro-Win64-Shipping.exe
    - Titanfall2.exe
    - BioShockInfinite.exe
    - Dungeonhaven-Win64-Shipping.exe
    - Borderlands2.exe
    - TheDivision2.exe
    - Back4Blood.exe
    - OUTRIDERS-Win64-Shipping.exe
    - FactoryGame-Win64-Shipping.exe
    - Raft.exe
    - EliteDangerous64.exe
    - starwarssquadrons.exe
    - MCC-Win64-Shipping.exe
    - ReadyOrNot-Win64-Shipping.exe
    - DyingLightGame.exe
    - Cyberpunk2077.exe
    - CoreKeeper.exe
    - Wonderlands.exe
    - SporeApp.exe
    - StardewModdingAPI.exe
    - RustClient.exe
    - InsurgencyClient-Win64-Shipping.exe
    - javaw.exe
    - Aperion-Win64-Shipping.exe
    - eldenring.exe
    - TY.exe
    - DSPGAME.exe
    - Astro-Win64-Shipping.exe
    - TheForest.exe
    - SpaceEngineers.exe
    - XboxPcApp.exe
    - SpaceEngineers.exe
    - NMS.exe
    - SkyrimSE.exe
    - Pandemic.exe
    - Dauntless-Win64-Shipping.exe
    - Generals.exe
    - Darktide.exe
    - ScrapMechanic.exe
    - Dwarf Fortress.exe
    - dayofinfamy_x64.exe
    - PathOfExileSteam.exe
    - GTFO.exe
  3:
    - runelite.exe
    - system
    - deej.unmapped
  4: firefox.exe 
  
# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: true

# settings for connecting to the arduino board
com_port: COM3
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default
